# Generated by Django 4.2.30 on 2026-05-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='fit_notes',
            field=models.TextField(max_length=500),
        ),
    ]
