# Generated by Django 4.2.30 on 2026-05-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoe_fit_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='use_case',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='fit_notes',
            field=models.TextField(max_length=700),
        ),
    ]
