# Generated by Django 4.2.30 on 2026-05-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_remove_shoe_use_case_alter_shoe_fit_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image_url',
            field=models.CharField(default='shoes/default.jpg', max_length=200),
        ),
    ]
