# Generated by Django 4.2.30 on 2026-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_shoe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='fit_notes',
            field=models.TextField(max_length=1500),
        ),
    ]
