# Generated by Django 4.2.30 on 2026-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_alter_shoe_fit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='retaileroffer',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
