# Generated by Django 4.2.30 on 2026-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_retaileroffer_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeGuides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('shoe', models.ManyToManyField(to='shoes.shoe')),
            ],
        ),
    ]
