# Generated by Django 4.2.30 on 2026-06-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_shoeguides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoeGuides',
            new_name='ShoeGuide',
        ),
    ]
