# Generated by Django 4.2.30 on 2026-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_rename_shoeguides_shoeguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeguide',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shoeguide',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoeguide',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoeguide',
            name='shoe',
            field=models.ManyToManyField(blank=True, to='shoes.shoe'),
        ),
    ]
