# Generated by Django 4.2.30 on 2026-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0010_shoeguide_date_shoeguide_slug_shoeguide_updated_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeguide',
            name='short_description',
            field=models.CharField(blank=True),
        ),
    ]
