# Generated by Django 4.2.30 on 2026-06-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0011_shoeguide_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('example', models.CharField(max_length=500)),
            ],
        ),
    ]
