# Generated by Django 4.2.30 on 2026-06-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_dictionary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='example',
            field=models.TextField(blank=True),
        ),
    ]
