# Generated by Django 4.2.30 on 2026-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_alter_dictionary_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
