# Generated by Django 4.2.30 on 2026-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0014_dictionary_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
