# Generated by Django 4.2.30 on 2026-06-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0015_alter_dictionary_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoeGuide',
            new_name='Guide',
        ),
    ]
