# Generated by Django 4.2.30 on 2026-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0016_rename_shoeguide_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='heading',
            field=models.CharField(choices=[('BALANCE AND BODY POS', 'Balance and Body Position'), ('FOOTWORK AND HANDHOLDS', 'Footwork and Handholds'), ('MOVEMENT AND TECHNIQUE', 'Movement and Technique'), ('ROUTE AND CLIMBING STYLE', 'Route and Climbing Style')], max_length=200),
        ),
    ]
