# Generated by Django 4.2.30 on 2026-07-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0017_alter_dictionary_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='heading',
            field=models.CharField(choices=[('BALANCE AND BODY POSITION', 'Balance and Body Position'), ('FOOTWORK AND HANDHOLDS', 'Footwork and Handholds'), ('MOVEMENT AND TECHNIQUE', 'Movement and Technique'), ('ROUTE AND CLIMBING STYLE', 'Route and Climbing Style')], max_length=200),
        ),
    ]
