# Generated by Django 4.2.30 on 2026-07-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_category_image_alter_dictionary_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(default='shoes/default.jpg', max_length=200),
        ),
    ]
