# Generated by Django 4.2.30 on 2026-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0019_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='short_description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
